version: "3.5"

services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - db
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: {}

networks:
  db:
    driver: bridge