#!/usr/bin/env bash

set -e

export PGHOST="${POSTGRES_HOST}"
export PGPORT="${POSTGRES_PORT}"
export PGUSER="${POSTGRES_USER}"
export PGPASSWORD="${POSTGRES_PASSWORD}"
export PGDATABASE="${POSTGRES_DB}"

PATH_WORKSPACE="/var/lib/postgresql"
PATH_BACKUPS="${PATH_WORKSPACE}/backups"