#!/usr/bin/env bash

set -e

echo "Checking if remote exists..."
git ls-remote --exit-code template

if test $? = 0; then
    echo "Remote not found. Adding remote template..."
    git remote add template https://github.com/achillesrasquinha/docker-template
fi

echo "Fetching updates..."
git fetch --all

echo "Merging changes..."
git merge template/develop --allow-unrelated-histories