#!/usr/bin/env bash

set -e

git remote add template https://github.com/achillesrasquinha/docker-template

echo "Fetching updates..."
git fetch --all

echo "Merging changes..."
git merge template/develop